ojob:
  sequential: true

jobs:
  #---------------
  - name: Stop all
    exec: |
      try {
        __pm.nodes = io.readFile(global.ROJOB.MASTERFILE).rojobs;
        __pm.stop = {};
      } catch(e) {
        __pm.error = String(e);
      }

  #-----------
  - name: Stop
    exec: |
      log("Stopping " + args.host + ":" + args.port);
      $rest().post("http://" + args.host + ":" + args.port + "/run", "rojob/stop.yaml");
      exit(0);

todo:
  - name: Stop all
  - name: Stop
    args: __pm.nodes
