FROM openaf/openaf:nightly_arm

ADD  run /openaf/roJob/run
COPY rojob.js /openaf/roJob/rojob.js
COPY roJob.yaml /openaf/roJob/roJob.yaml
COPY .odoc.db /openaf/roJob/.odoc.db
COPY roJobService.js /openaf/roJob/roJobService.js

RUN mkdir /work\
 && mkdir /logs

ENV OPENAF=/openaf/roJob/roJobService.js
ENV WORK=/work
ENV LISTEN=0.0.0.0

WORKDIR /openaf/roJob
