ojob:
  async: true
  logToConsole: true

todo:
  - Detect OS
  - Detect Python version
  - Generate API key
  - Generate Python script
  - Generate OS script
  - Generate Watchdog oJob

jobs:
  #----------------
  - name: Detect OS
    exec: |
      ow.loadFormat();
      global.os = (ow.format.getOS().match(/windows/i) ? "win" : "unix");
      log("OS type: " + global.os);

  #----------------------------
  - name: Detect Python version
    exec: |
      var res = $sh("python --version").get(0);
      res = res.stdout + res.stderr;
      global.python = (res.match(/ 2\./) ? 2 : 3);
      log("Python version: " + global.python);

  #-----------------------
  - name: Generate API key
    exec: |
      if (isUnDef(args.APIKEY) && io.fileExists(getOPackPath("roJob") + "/.apikey")) 
        args.APIKEY = io.readFileString(getOPackPath("roJob") + "/.apikey");
      var key = ( isDef(args.APIKEY) ? args.APIKEY : sha512(genUUID()) );
      key = key.trim().replace(/\n/g, "");
      io.writeFileString(getOPackPath("roJob") + "/.apikey", key);
      global.key = key;
      log("APIKEY: " + key);

  #-----------------------------
  - name: Generate Python script 
    deps:
      - Detect Python version
      - Generate API key
    exec: |
      var script;
      if (global.python == 2) {
        script = io.readFileString(getOPackPath("roJob") + "/rojob.py.sample2");
      } else {
        script = io.readFileString(getOPackPath("roJob") + "/rojob.py.sample3");
      }

      script = script.replace(/APIKEY = \"[^"]*\"/, "APIKEY = \"" + global.key + "\"");
      io.writeFileString(getOPackPath("roJob") + "/rojob.py", script);
      log("Generated " + getOPackPath("roJob") + "/rojob.py.");

  #-------------------------
  - name: Generate OS script
    deps:
      - Detect OS
      - Generate Python script
    exec: |
      var script = "";
      if (global.os == "win") {
         script += "@echo off\n\n";
         script += "python " + getOPackPath("roJob") + "\\rojob.py %*\n";
         io.writeFileString(getOPackPath("roJob") + "\\rojob.bat", script);
         log("Generated rojob.bat.");
      } else {
         script += "#!/bin/sh\n\n";
         script += "python " + getOPackPath("roJob") + "/rojob.py \"$@\"\n";
         io.writeFileString(getOPackPath("roJob") + "/rojob.sh", script);
         sh("chmod u+x " + getOPackPath("roJob") + "/rojob.sh");
         log("Generated rojob.sh.");
      }

  #-----------------------------
  - name: Generate Watchdog oJob
    deps:
      - Detect OS
    exec: |
      args.CDISC = _$(args.CDISC).default("127.0.0.1:8787");
      args.PORTS = _$(args.PORTS).default("8787,8788");
      args.PORTS = args.PORTS.split(/,/);

      io.writeFileString(getOPackPath("roJob") + "/watchdog.yaml", templify(io.readFileString(getOPackPath("roJob") + "/watchdog.yaml.sample"), { 
         win: (global.os == "win"), 
         opackHome: getOPackPath("roJob").replace(/\\/g, "/"),
         openafHome: getOpenAFPath().replace(/\\/g, "/"),
         cdisc: args.CDISC,
         ports: args.PORTS
      }));
      log("Generated watchdog.yaml.");

